Server on port 3000
Database is connected
Server on port 8000
Database is connected
node:events:355
      throw er; // Unhandled 'error' event
      ^

Error: Connection lost: The server closed the connection.
    at Protocol.end (/home/servidores/node_modules/mysql/lib/protocol/Protocol.js:112:13)
    at Socket.<anonymous> (/home/servidores/node_modules/mysql/lib/Connection.js:94:28)
    at Socket.<anonymous> (/home/servidores/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:390:22)
    at endReadableNT (node:internal/streams/readable:1307:12)
    at processTicksAndRejections (node:internal/process/task_queues:81:21)
Emitted 'error' event on Connection instance at:
    at Connection._handleProtocolError (/home/servidores/node_modules/mysql/lib/Connection.js:423:8)
    at Protocol.emit (node:events:378:20)
    at Protocol._delegateError (/home/servidores/node_modules/mysql/lib/protocol/Protocol.js:398:10)
    at Protocol.end (/home/servidores/node_modules/mysql/lib/protocol/Protocol.js:116:8)
    at Socket.<anonymous> (/home/servidores/node_modules/mysql/lib/Connection.js:94:28)
    [... lines matching original stack trace ...]
    at processTicksAndRejections (node:internal/process/task_queues:81:21) {
  fatal: true,
  code: 'PROTOCOL_CONNECTION_LOST'
}
Server on port 8000
Database is connected
Server on port 8000
Database is connected
Server on port 8000
Database is connected
node:events:355
      throw er; // Unhandled 'error' event
      ^

Error: Connection lost: The server closed the connection.
    at Protocol.end (/home/servidores/node_modules/mysql/lib/protocol/Protocol.js:112:13)
    at Socket.<anonymous> (/home/servidores/node_modules/mysql/lib/Connection.js:94:28)
    at Socket.<anonymous> (/home/servidores/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:390:22)
    at endReadableNT (node:internal/streams/readable:1307:12)
    at processTicksAndRejections (node:internal/process/task_queues:81:21)
Emitted 'error' event on Connection instance at:
    at Connection._handleProtocolError (/home/servidores/node_modules/mysql/lib/Connection.js:423:8)
    at Protocol.emit (node:events:378:20)
    at Protocol._delegateError (/home/servidores/node_modules/mysql/lib/protocol/Protocol.js:398:10)
    at Protocol.end (/home/servidores/node_modules/mysql/lib/protocol/Protocol.js:116:8)
    at Socket.<anonymous> (/home/servidores/node_modules/mysql/lib/Connection.js:94:28)
    [... lines matching original stack trace ...]
    at processTicksAndRejections (node:internal/process/task_queues:81:21) {
  fatal: true,
  code: 'PROTOCOL_CONNECTION_LOST'
}
Server on port 8000
Database is connected
node:events:355
      throw er; // Unhandled 'error' event
      ^

Error: Connection lost: The server closed the connection.
    at Protocol.end (/home/servidores/node_modules/mysql/lib/protocol/Protocol.js:112:13)
    at Socket.<anonymous> (/home/servidores/node_modules/mysql/lib/Connection.js:94:28)
    at Socket.<anonymous> (/home/servidores/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:390:22)
    at endReadableNT (node:internal/streams/readable:1307:12)
    at processTicksAndRejections (node:internal/process/task_queues:81:21)
Emitted 'error' event on Connection instance at:
    at Connection._handleProtocolError (/home/servidores/node_modules/mysql/lib/Connection.js:423:8)
    at Protocol.emit (node:events:378:20)
    at Protocol._delegateError (/home/servidores/node_modules/mysql/lib/protocol/Protocol.js:398:10)
    at Protocol.end (/home/servidores/node_modules/mysql/lib/protocol/Protocol.js:116:8)
    at Socket.<anonymous> (/home/servidores/node_modules/mysql/lib/Connection.js:94:28)
    [... lines matching original stack trace ...]
    at processTicksAndRejections (node:internal/process/task_queues:81:21) {
  fatal: true,
  code: 'PROTOCOL_CONNECTION_LOST'
}
Server on port 8000
Database is connected
node:events:355
      throw er; // Unhandled 'error' event
      ^

Error: Connection lost: The server closed the connection.
    at Protocol.end (/home/servidores/node_modules/mysql/lib/protocol/Protocol.js:112:13)
    at Socket.<anonymous> (/home/servidores/node_modules/mysql/lib/Connection.js:94:28)
    at Socket.<anonymous> (/home/servidores/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:390:22)
    at endReadableNT (node:internal/streams/readable:1307:12)
    at processTicksAndRejections (node:internal/process/task_queues:81:21)
Emitted 'error' event on Connection instance at:
    at Connection._handleProtocolError (/home/servidores/node_modules/mysql/lib/Connection.js:423:8)
    at Protocol.emit (node:events:378:20)
    at Protocol._delegateError (/home/servidores/node_modules/mysql/lib/protocol/Protocol.js:398:10)
    at Protocol.end (/home/servidores/node_modules/mysql/lib/protocol/Protocol.js:116:8)
    at Socket.<anonymous> (/home/servidores/node_modules/mysql/lib/Connection.js:94:28)
    [... lines matching original stack trace ...]
    at processTicksAndRejections (node:internal/process/task_queues:81:21) {
  fatal: true,
  code: 'PROTOCOL_CONNECTION_LOST'
}
